import Head from 'next/head'
import { AuthLayoutSimple } from '@multiverse-org/ui/src/components/molecules/AuthLayout'
import { LoginForm } from '@multiverse-org/ui/src/components/templates/LoginForm'

export default function Login() {
  return (
    <>
      <Head>
        <title>Multiverse | Login | Karthick Ragavendran</title>{' '}
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <AuthLayoutSimple title="Login">
          <LoginForm />
        </AuthLayoutSimple>
      </main>
    </>
  )
}
