import Head from 'next/head'
import { CreateStory } from '@multiverse-org/ui/src/components/templates/CreateStory'

export default function CreateStoryPage() {
  return (
    <>
      <Head>
        <title>Create Story | Karthick Ragavendran</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <CreateStory />
      </main>
    </>
  )
}
