import Head from 'next/head'
import { PlayStory } from '@multiverse-org/ui/src/components/templates/PlayStory'
import { useRouter } from 'next/router'
import { AlertSection } from '@multiverse-org/ui/src/components/organisms/AlertSection'
import { Container } from '@multiverse-org/ui/src/components/atoms/Container'

export default function PlayPage() {
  const { query } = useRouter()
  const storyId = Number(query.storyId)

  if (isNaN(storyId)) {
    return <AlertSection>(`Invalid storyId: ${query.storyId}`)</AlertSection>
  }

  return (
    <>
      <Head>
        <title>Play story</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Container>
          <PlayStory storyId={storyId} />
        </Container>
      </main>
    </>
  )
}
