import Head from 'next/head'
import { StoryMain } from '@multiverse-org/ui/src/components/templates/StoryMain'
import { useRouter } from 'next/router'
import { AlertSection } from '@multiverse-org/ui/src/components/organisms/AlertSection'
import { Container } from '@multiverse-org/ui/src/components/atoms/Container'
import {
  UserStoryType,
  useUserStoryLazyQuery,
  useUserStoryQuery,
} from '@multiverse-org/network/src/gql/generated'
import { useUserStore } from '@multiverse-org/store/user'
import { useEffect } from 'react'
import { Button } from '@multiverse-org/ui/src/components/atoms/Button'

export default function PlayPage() {
  const { query } = useRouter()
  const storyId = Number(query.storyId)

  if (isNaN(storyId)) {
    return <AlertSection>(`Invalid storyId: ${query.storyId}`)</AlertSection>
  }

  return (
    <>
      <Head>
        <title>Play story | Karthick Ragavendran</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Container>
          <StoryMain storyId={storyId} />
        </Container>
      </main>
    </>
  )
}
