import Head from 'next/head'
import { Container } from '@multiverse-org/ui/src/components/atoms/Container'
import { ResetPassword } from '@multiverse-org/ui/src/components/templates/ResetPassword'
import { AuthLayout } from '@multiverse-org/ui/src/components/molecules/AuthLayout'

export default function ResetPasswordPage() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <AuthLayout title="Reset Password">
          <ResetPassword />
        </AuthLayout>
      </main>
    </>
  )
}
